### ISSUE TITLE
Running BounShell without first running IE causes an error

### ISSUE THREAD

**Issue by Atreidae** [Atreidae/BounShell#21]
The expected registry key is missing. I noted @PatRichard has a fix in Set-CsFeatures where if it hasn't already been set, he forces it to zero. Might be worth looking at

**Comment by Atreidae** [comment]
![image](https://user-images.githubusercontent.com/8736291/69899423-d0bac500-13b9-11ea-910c-3c0f7d85cf8f.png)

**Comment by patrichard** [comment]
Yep – I had to come up with a workaround in Set-CsFeatures.ps1 for this.

 if ((Get-Item -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings').Property -NotContains 'ProxyEnable'){
    $null = New-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' -Name ProxyEnable -Value 0
  }

**Comment by Atreidae** [comment]
Thanks Pat. Appreciate the help!

**Comment by Atreidae** [comment]
Hmm, seems it's still trying to kick off the first run

I ended up using the -UseBasicParsing flag.
