### ISSUE TITLE
Powershell ISE detection sucks

### ISSUE THREAD

**Issue by Atreidae** [Atreidae/BounShell#3]
Using the PS.ISE detection as part of the module manifest give a bad user experience.

> PS C:\Users\foo.bar> import-module bounshell
> import-module : The specified module 'bounshell' was not loaded because no valid module file was found in any module directory.
> 

Attempting to import the module gives a better error message, but its still horrible.

> PS C:\Users\foo.bar> import-module bounshell
> import-module : The name of the current Windows PowerShell host is: 'ConsoleHost'. The module
> PS C:\Users\foo.bar\SfB-Software\bounshell\bounshell.psd1' requires the following Windows PowerShell host: 'Windows PowerShell ISE Host'.

I know I should let PowerShell do what it's designed to do. but it sucks. So I'm going to handle it nativley

**Comment by Atreidae** [comment]
Fixed this in 587ffe1130dbcc03ffb57412d346f626932c41a1

**Comment by greiginsydney** [comment]
FYI, ISE reports the screen-width = 0. That's my go-to test.

`$UserScreenWidth = [int](get-host).UI.rawui.Windowsize.Width`

**Comment by Atreidae** [comment]
Thanks for that. I'm presently checking to see the the $PSISE variable is loaded. As we need to manipulate it  later to add the add-ons menu options. So if its not there, the ~script~ module isnt going to work very well anyway

**Comment by Atreidae** [comment]
Nice trick to remember though.

**Comment by Atreidae** [comment]
Closing this issue
